using Terraria;
using Terraria.GameContent.Creative;
using Terraria.ModLoader;

namespace ClickerClass.Items
{
	/// <summary>
	/// Convenience class that every clicker class related item inherits from
	/// </summary>
	public abstract class ClickerItem : ModItem
	{
		/// <summary>
		/// Call this in the inherited class as base.SetStaticDefaults() at the start of SetStaticDefaults
		/// </summary>
		public override void SetStaticDefaults()
		{
			ClickerSystem.RegisterClickerItem(this);

			//Set sacrifies to 1 by default. Let inheriting classes overwrite it if necessary
			//Most things in this mod are unstackable items, those all have 1
			CreativeItemSacrificesCatalog.Instance.SacrificeCountNeededByItemId[Type] = 1;
		}

		/// <summary>
		/// Call in <see cref="ModItem.SetDefaults"/> for a clicker item to assign it an accessory type, so that items with that accessory type cannot be equipped together
		/// </summary>
		/// <param name="item">The clicker class item</param>
		public static void SetAccessoryType(Item item, ClickerAccessoryType accessoryType)
		{
			if (ClickerSystem.IsClickerItem(item, out ClickerItemCore clickerItem))
			{
				clickerItem.accessoryType = accessoryType;
			}
		}

		/// <summary>
		/// Call in <see cref="ModItem.SetDefaults"/> for a clicker item to make it display total click count in the tooltip
		/// </summary>
		/// <param name="item">The clicker class item</param>
		public static void SetDisplayTotalClicks(Item item)
		{
			if (ClickerSystem.IsClickerItem(item, out ClickerItemCore clickerItem))
			{
				clickerItem.isClickerDisplayTotal = true;
			}
		}
		
		/// <summary>
		/// Call in <see cref="ModItem.SetDefaults"/> for a clicker item to make it display total money generated by item
		/// </summary>
		/// <param name="item">The clicker class item</param>
		public static void SetDisplayMoneyGenerated(Item item)
		{
			if (ClickerSystem.IsClickerItem(item, out ClickerItemCore clickerItem))
			{
				clickerItem.isClickerDisplayMoneyGenerated = true;
			}
		}
	}
}
