using Microsoft.Xna.Framework;
using System.Collections.Generic;
using Terraria.UI;

namespace ClickerClass.UI
{
	public abstract class InterfaceResource : GameInterfaceLayer
	{
		/// <summary>
		/// Offset generated by UI gauges. Each gauge (can) increment the value allowing for multiple gauges to display at once without overlap
		/// </summary>
		public static int ClickerGaugeOffset { get; private set; }

		/// <summary>
		/// Should only be called if Main.ingameOptionsWindow || Main.InGameUI.IsVisible is false (see call site of <see cref="ResetClickerGaugeOffset"/>)
		/// </summary>
		/// <param name="amount">Amount to offset by</param>
		public static void IncreaseClickerGaugeOffset(int amount = 26)
		{
			ClickerGaugeOffset += amount;
		}

		public static void ResetClickerGaugeOffset()
		{
			ClickerGaugeOffset = 0;
		}

		public InterfaceResource(string name, InterfaceScaleType scaleType) : base(name, scaleType) { }
		public abstract int GetInsertIndex(List<GameInterfaceLayer> layers);
		public virtual void Update(GameTime gameTime) { }
	}
}
